version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    image: maayanlab/d2h2:1.2.5
    environment:
      - ROOT_PATH=/D2H2/
      - BASE_PATH=https://maayanalab.cloud
      - ENDPOINT=https://minio.dev.maayanlab.cloud/
      - DEBUG=False
      - BASE_URL=d2h2/data
    ports:
      - 5000:80
