version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    image: maayanlab/d2h2:1.3.02
    environment:
      - ROOT_PATH=/
      - BASE_PATH=data
      - ENDPOINT=https://d2h2.s3.amazonaws.com/
      - DEBUG=False
      - BASE_URL=data
    ports:
      - 5000:5000
