version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    image: giacomomarino/d2h2:1.1.4
    environment:
      - ROOT_PATH=/D2H2/
      - BASE_PATH=https://maayanalab.cloud
      - DEBUG=true
      - BASE_URL=d2h2/data
    ports:
      - 5000:80
