version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    image: giacomomarino/d2h2:0.1.0
    environment:
      - ROOT_PATH=/
      - BASE_PATH=https://maayanalab.cloud
      - DEBUG=false
      - BASE_URL=d2h2/data
    ports:
      - 8080:80
